name: Publish Library to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Publish all KMP targets to GitHub Packages
        run: ./gradlew :zscanner:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
